In [ ]:
arr = np.array([    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print(arr)
print(arr.ndim)   # Number of dimensions
print(arr.shape)  # (Layers, Rows, Columns)
print(arr.size)   # Total number of elements
print(arr[0])        # First layer
print(arr[1])        # Second layer
print(arr[0][1])     # Second row of first layer
print(arr[1][0][0])  # Element 9

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
12
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[4 5 6]
7


In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]


In [ ]:
arr = np.zeros((3,3))
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr = np.arange(1,13)
print(arr.reshape(4,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr.shape)
print(arr.size)

(2, 3)
6


In [ ]:
arr = np.linspace(1, 10, 5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
arr = np.full((3, 4), 7)
print(arr)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
arr = np.array([[10, 20, 30],[40, 50, 60]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.T)

(2, 3)
2
6
int64
[[10 40]
 [20 50]
 [30 60]]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(2, 3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr_1 = np.reshape(arr,(3,2))
print(new_arr_1)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
arr_3d = np.array([1,2,3,4,5,6,7,8])
new_arr_3d = arr_3d.reshape(2,2,2)
print(new_arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr[1:5])
print(arr[:4])
print(arr[2:])
print(arr[::2])

[20 30 40 50]
[10 20 30 40]
[30 40 50 60]
[10 30 50]


In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr[1:5])
print(arr[:4])
print(arr[2:])
print(arr[::2])

[20 30 40 50]
[10 20 30 40]
[30 40 50 60]
[10 30 50]


In [ ]:
import numpy as np

# Random number
print(np.random.rand())

# Random numbers
print(np.random.rand(5))

# Random integers
print(np.random.randint(1, 11, 5))

# Random choice
subjects = ["DBMS", "Python", "Java", "ML"]
print(np.random.choice(subjects))

# Normal distribution
print(np.random.normal(50, 10, 5))

# Uniform distribution
print(np.random.uniform(10, 20, 5))

# Bernoulli random variable
print(np.random.binomial(1, 0.5))

# Binomial random variable
print(np.random.binomial(10, 0.7))

# Poisson random variable
print(np.random.poisson(4, 5))

# Exponential random variable
print(np.random.exponential(2, 5))

0.8917026083068519
[0.20615992 0.19455804 0.7549981  0.4241346  0.18538225]
[7 6 3 4 3]
Java
[52.04743947 56.44670363 35.71602708 59.69565412 40.92399487]
[10.39001114 17.80170216 19.6056361  12.81036057 16.40255642]
0
7
[3 4 2 2 4]
[0.08713681 0.37883142 1.85816082 1.8978599  0.53855143]


In [ ]:
import numpy as np

# Create a NumPy array
marks = np.array([75, 82, 90, 68, 95, 88, 79])

print("Original Array:", marks)
# Sort
print("Sorted Array:", np.sort(marks))
# Sum
print("\nSum:", np.sum(marks))

# Mean (Average)
print("Mean:", np.mean(marks))

# Median
print("Median:", np.median(marks))

# Maximum Value
print("Maximum:", np.max(marks))

# Minimum Value
print("Minimum:", np.min(marks))

# Range
print("Range:", np.ptp(marks))

# Standard Deviation
print("Standard Deviation:", np.std(marks))

# Variance
print("Variance:", np.var(marks))

# Index of Maximum Value
print("Index of Maximum:", np.argmax(marks))

# Index of Minimum Value
print("Index of Minimum:", np.argmin(marks))

# Percentiles
print("25th Percentile:", np.percentile(marks, 25))
print("50th Percentile:", np.percentile(marks, 50))
print("75th Percentile:", np.percentile(marks, 75))

Original Array: [75 82 90 68 95 88 79]
Sorted Array: [68 75 79 82 88 90 95]

Sum: 577
Mean: 82.42857142857143
Median: 82.0
Maximum: 95
Minimum: 68
Range: 27
Standard Deviation: 8.633111388421788
Variance: 74.53061224489797
Index of Maximum: 4
Index of Minimum: 3
25th Percentile: 77.0
50th Percentile: 82.0
75th Percentile: 89.0


In [ ]:
import numpy as np
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(arr[0:2,1:3])
print(arr[1,:])
print(arr[:,2])

[[20 30]
 [50 60]]
[40 50 60]
[30 60 90]


In [ ]:
import numpy as np
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(arr[0,:,:])
print(arr[1,1,:])
print(arr[:,:,0])

[[1 2 3]
 [4 5 6]]
[10 11 12]
[[ 1  4]
 [ 7 10]]


In [ ]:
import numpy as np

a = np.array([10,20,30])
b = np.array([2,4,5])
print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)
print("Floor Division:", a//b)
print("Modulus:", a%b)
print("Power:", a**2)

Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]
Floor Division: [5 5 6]
Modulus: [0 0 0]
Power: [100 400 900]


In [ ]:
A = np.arange(6).reshape(2, 3)   # shape (2, 3)
B = np.ones((2, 3), dtype=int)

print('A:\n', A)
print('A + B (element-wise add):\n', A + B)
print('A.T  (transpose -> shape', A.T.shape, '):\n', A.T)
print('A.reshape(3, 2):\n', A.reshape(3, 2))
print('A.flatten():', A.flatten())

A:
 [[0 1 2]
 [3 4 5]]
A + B (element-wise add):
 [[1 2 3]
 [4 5 6]]
A.T  (transpose -> shape (3, 2) ):
 [[0 3]
 [1 4]
 [2 5]]
A.reshape(3, 2):
 [[0 1]
 [2 3]
 [4 5]]
A.flatten(): [0 1 2 3 4 5]


In [ ]:
import numpy as np
import numpy.linalg as la          # inv, norm, eig, solve, matrix_rank
import matplotlib.pyplot as plt

np.set_printoptions(precision=3, suppress=True)   # tidy array printing
np.random.seed(42)
print('Setup complete. NumPy', np.__version__)

Setup complete. NumPy 2.0.2


In [ ]:
scalar = np.array(5)                  # 0-D: a single number
vector = np.array([2, 5, 1])          # 1-D: a list of numbers
matrix = np.array([[1, 2], [3, 4]])   # 2-D: rows x columns
tensor = np.ones((3, 2, 2))           # n-D: a stack of matrices

# .ndim = number of dimensions, .shape = size along each dimension
for name, arr in [('scalar', scalar), ('vector', vector),
                  ('matrix', matrix), ('tensor', tensor)]:
    print(f'{name:7s} ndim={arr.ndim}  shape={arr.shape}')

scalar  ndim=0  shape=()
vector  ndim=1  shape=(3,)
matrix  ndim=2  shape=(2, 2)
tensor  ndim=3  shape=(3, 2, 2)


In [ ]:
print(53)

1
